version: '3'

services:
  zsz-rbot:
    build:
      context: .
    image: registry.cn-shenzhen.aliyuncs.com/zszweb/zsz-rbot:latest
    container_name: zsz-rbot
    restart: always
    ports:
      - "9527":"9527"
    volumes:
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./client_config:/app/client_config
      - ./logs/log_r_client.log.log:/var/log/log_r_client.log.log
      - ./logs/log_r_client.log_err.log:/var/log/log_r_client_err.log.log
